### ISSUE TITLE
No traffic/access logs for apps mapped to internal domains (C2C routing)

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/silk-release#14]
I have a backend and a frontend. There is a tcp policy in place between the two (port 8080 because that's where it is listening on the backend). I didn't know how to discover an IP/hostname for the backend, so I mapped it to a route on an internal domain (e.g. `backend.apps.internal`).
It works fine if I use `http://backend.apps.internal:8080` as a service url in the frontend. But no logs, so I'm kind of wondering if I did this right.

It would be good to have access logs like the `[RTR/xx]` logs for such apps, otherwise you don't really know (as a user) when they are being accessed.

**Comment by shalako** [comment]
Hi @dsyer 

1. [Create a policy](https://docs.pivotal.io/pivotalcf/2-4/devguide/deploy-apps/cf-networking.html#add-policy) to enable the frontend app to reach the backend over tcp on port 8080
2. Create an internal route for the backend
3. Configure your frontend app to communicate with the backend on `http://backend.apps.internal:8080`

That is the expected workflow and should work. Was there anything challenging with discovering that workflow?

Regarding validation that it works, I would expect your backend app to log when it receives a request. Would you like to avoid instrumenting your apps in this way, and rely on the platform to verify that your backend app responded with a 200 status code?

Once we've got C2C requests transiting client and server-side service mesh sidecar proxies, we could expose access logs for those proxies to the app dev. Which messages would you expect to see?

- If you tailed the logs for only the backend app and sent a request through the frontend, would you expect to see the access log message for the egress request through the sidecar for the frontend app, as well as the access log message for the ingress through the sidecar for the backend app? 
- What if you tailed the logs for only the frontend app? Would you expect to see the access log messages for platform ingress, container ingress, and container egress?

**Comment by dsyer** [comment]
> Was there anything challenging with discovering that workflow?

I guess the flow was never explicitly described in 3 easy steps like that. I found bits of information about all the steps in different places and had to guess/glue it together.

> Would you like to avoid instrumenting your apps in this way

Yes, but only to the same extent that I can for an app that is on an external route. Why should it matter if I use `cfapps.io` or `apps.internal` as the domain (as far as being able to see incoming requests). The app is the same underneath, so I wouldn't expect to have to instrument it differently, depending on the routing choice I make.

> would you expect to see the access log message for the egress request through the sidecar for the frontend app

No. Not necessarily anyway. Just looking for the something on the backend app to make it behave (for a user) the same as if it had an external route.

> If you tailed the logs for only the backend app and sent a request through the frontend

Not looking for anything on the front end really (which isn't to say it wouldn't be useful sometimes). I just want to know that there is some traffic, and basic stuff like HTTP method, status, B3 headers.

**Comment by shalako** [comment]
Thank for your responses, Dave! We'll explore how to improve our docs to make the above workflow more explicit. 

Your expectations for parity of user experience between use of external and internal routes is totally reasonable. I've recorded your suggestions and when we get to implementing the enhancement we'll reach out to let you know.

**Comment by shalako** [comment]
For internal use: https://pcf.aha.io/features/NTWRK-89

**Comment by cameronmoreau** [comment]
Hey @dsyer 
In the mean time, we have a doc describing [enabling kernel logs](https://github.com/cloudfoundry/silk-release/blob/develop/docs/traffic_logging.md) for overlay traffic. Hope this helps!

**Comment by ameowlia** [comment]
Hi all, 

We are closing this issue because we are not going to add this feature to silk-release. We intend to enable this for workloads deployed to K8s via CF+Eirini. 

Thanks, 
@ameowlia and @mike1808 , CF Networking Program Members
