### ISSUE TITLE
Feature Request container traffic volume logging

### ISSUE THREAD

**Issue by ionphractal** [cloudfoundry/silk-release#16]
## Issue

Not sure if this is the right place to do so, but I would like to propose a feature request to add logging for container traffic volume. Also, if there's already a solution for this, I'd be happy to hear from it.

## Context

IaaS providers may bill its customers for used traffic volume. To distribute costs across app owners by their use/fair share, it is necessary to have accurate data about sent/received volume for each app/container.

## Expected result

Traffic volume (rx/tx/sum) of a container should be emitted as a metric in a way that it can be associated with an app/space/org.

## Current result

Please correct me if I'm wrong, but as far as I understood it, netmon currently only emits metrics on cell level without any association to an app/container. The iptables-logger also does not have any information about the transferred volume of a connection it logs (iptables only loggs the first connection package). Another thing I've thought about is HttpStartStop events, which kind of give a hint about traffic volume (content length), but I wonder if this is so accurate. And it only includes traffic that passes the gorouters, which for example does not include app-to-external or c2c communications.

## Possible Fix

Not sure if this can be done in netmon or iptables-logger or if it needs to be done inside silk.

Looking forward to your feedback!

**Comment by rodolfo2488** [comment]
Hi @ionphractal, 

Thank you for submitting your request. We found this issue https://github.com/cloudfoundry/cf-networking-release/issues/64 on the cf-networking-release repository that seems similar to this. We have not prioritized it yet, but would you help me identify if this is what you are looking for or what are the differences you have from that request. There is a clear acceptance criteria in that issue you might want to give feedback. 

That work has not been prioritized but will add you in the list of people interested if you feel that will solve the business requirement you are looking to solve.

feel free to close this issue and reference it in the other issue if you feel like they are related. 

Thanks!
@rodolfo2488, CF Networking Program Members

**Comment by ionphractal** [comment]
@rodolfo2488 Yes, looks like the same topic. Thanks!
closed in favor of https://github.com/cloudfoundry/cf-networking-release/issues/64
