### ISSUE TITLE
Application instances crash which is configured with network-policy is restarted

### ISSUE THREAD

**Issue by sravankumar777** [cloudfoundry/silk-release#18]
Thanks for submitting an issue to `cf-networking-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue
Application instances crashed when that particular application is restart having configured with network-policy. 

## Context
Our deployment has below releases deployed.
CF-Deployment v2.7.0
CF-Networking-Release v2.15.1
Silk-release v2.15.0

Performed restart of cells with the mentioned release versions. 
Some application instances were crash randomly on start operation. 
By checking more logs & troubleshooting, it is observed that applications(having multiple instances) assigned with network-policy did crash. However, other applications which are not assigned with network-policy did also crash. 

## Steps to Reproduce
1. Deploy an application with multiple instances(tested the case with 15 instances)
2. Assign a network policy to the deployed application.
3. Perform restart of the application may be 3-4 times. 

## Expected result
No application instances should be crashing after performing restart operation. 

## Current result
Some of application instances crash with the below error reason.

Application events:
```
cf events hello-go-app
...
2019-07-22T11:00:26.00+0900   app.crash                 hello-go-app   index: 13, reason: CRASHED, cell_id: 3f751a65-2d16-4870-b769-da9cb7dee3a9, instance: 802a2ba7-abaa-4fd1-7292-8fba, exit_description: failed to create container: external networker up: exit status 1
```

BBS logs:
```
{"timestamp":"2019-07-18T01:23:13.449677439Z","level":"info","source":"bbs","message":"bbs.request.crash-actual-lrp.complete","data":{"crash_reason":"failed to create container: external networker up: exit status 1","instance_key":{"instance_guid":"bb3ef128-93d9-40cb-7503-2264","cell_id":"7ac209e2-f986-4cda-b080-ac2f65037185"},"key":{"process_guid":"47ec3792-a916-4117-8775-edd94b79bece-6abe4c52-1689-4091-8acc-15e4fb346022","index":0,"domain":"cf-apps"},"session":"3873.1"}}
```

GARDEN logs:
```
{"timestamp":"2019-07-18T01:23:07.121882430Z","level":"error","source":"guardian","message":"guardian.create.external-networker-result","data":{"action":"up","error":"exit status 1","handle":"bb3ef128-93d9-40cb-7503-2264","session":"15","stderr":"cfnetworking: cni up failed: add network list failed: vpa response code: 500 with message: failed to force policy poll cycle: enforce: creating chain: iptables call: running [/sbin/iptables -t filter -N vpa--1563412987 --wait]: exit status 1: iptables: Chain already exists.\n and unlock: \u003cnil\u003e\n","stdin":"{\"Pid\":992395,\"Properties\":{\"app_id\":\"47ec3792-a916-4117-8775-edd94b79bece\",\"org_id\":\"3f5e86a5-2af4-45d9-852d-d7433078e0d4\",\"policy_group_id\":\"47ec3792-a916-4117-8775-edd94b79bece\",\"ports\":\"8080\",\"space_id\":\"c4b2e3f9-0bb5-432a-acfc-9f4e4b018612\"},\"netout_rules\":[{\"protocol\":1,\"networks\":[{\"start\":\"0.0.0.0\",\"end\":\"255.255.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]},{\"protocol\":2,\"networks\":[{\"start\":\"0.0.0.0\",\"end\":\"255.255.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]},{\"networks\":[{\"start\":\"0.0.0.0\",\"end\":\"100.73.3.255\"}]},{\"networks\":[{\"start\":\"100.73.5.0\",\"end\":\"100.73.55.255\"}]},{\"networks\":[{\"start\":\"100.73.64.0\",\"end\":\"100.89.255.255\"}]},{\"networks\":[{\"start\":\"100.90.8.0\",\"end\":\"255.255.255.255\"}]}],\"netin\":[{\"host_port\":0,\"container_port\":8080},{\"host_port\":0,\"container_port\":2222}]}","stdout":""}}
```
## Possible Fix
Fix is provided in [```silk-release``` v2.16.0](https://github.com/cloudfoundry/silk-release/commit/6c663816755c71cca89d862162f4b07c9e3fb469#diff-f52077249d0743b1baf3a82668f87f7a).
However the release notes were not clear mentioning about the fix or issue.

Also request to update the release notes for ```silk-release``` v2.13.0, v2.14.0 & v2.15.0 about the issue or bug introduced.

**Comment by sravankumar777** [comment]
We guess issue observed might be related to https://pvtl.force.com/s/article/diego-cell-garden-healthcheck-fails-and-becomes-unhealthy & this issue is probably fixed in silk-release v2.16.0.

**Comment by mike1808** [comment]
Hi @sravankumar777 , sounds like you may have a way forward by upgrading to silk release v2.16.0. As a note, you may want to bump to cf-networking-release v2.16.0 as well, as there are new features and fixes. Let us know if you're still seeing the problem after upgrading.

Thanks, 
@KauzClay  and @mike1808 , CF Networking Program Members

**Comment by sravankumar777** [comment]
Hi @mike1808,

Yes, we plan to bump with both silk-release and cf-networking-release v2.16.0.
I was requesting for update of release notes, as much of information is not clear like about the bug or the issue. 

So, if we can update the same information. It will be clear for other people as well, who plan to bump for any release between v2.12.0 & v2.16.0.

Thanks.

**Comment by mike1808** [comment]
Hey @sravankumar777 since we haven't received the response from you for a long time, we are going to close the issue. Feel free to reopen if the problem persists.

Thanks,
@KauzClay and @mike1808 , CF Networking Program Members

**Comment by sravankumar777** [comment]
@mike1808, we have updated both silk & cf-networking-release to v2.16.0. 
We did not see the error about applications being restarted.
However, we wanted to suggest about updating the release notes on bug information for previous releases to v2.16.0.
