### ISSUE TITLE
Synchronized polling from VXLAN policy agent and silk-daemon can cause heavy load on database

### ISSUE THREAD

**Issue by mcwumbly** [cloudfoundry/silk-release#26]
## Issue

A `silk-daemon` and a `vxlan-policy-agent` are deployed on each Diego Cells and continuously poll the policy-server and silk-controller which are backed by a SQL database. When large numbers of Diego Cells are deployed at the same time, all of them can end up with synchronized polling intervals, causing spikes in load on the database.

## Possible Fix

Perhaps it makes sense to introduce some jitter into the single-cycle function that gets called by the polling, and/or to introduce some random offset into the polling cycle duration itself.

## Context

In very large deployments (for example in a scaling test with 1200 Diego Cells), operators may set `max_in_flight` to a large number (like 50). This means that once a canary Diego Cell is successfully deployed, then groups of 50 Diego Cells deploy at a time.

The `silk-daemon` and `vxlan-policy-agent` are deployed on the Diego Cell and continuously poll the policy-server and silk-controller which are backed by a SQL database. For the Diego Cells that are deployed in one group, all 50 Diego Cells can end up with synchronized polling intervals, causing spikes in load on the database.

As a workaround, `max-in-flight` can be reduced or the database can be over-provisioned to handle these spikes.

Original discussion in [Cloud Foundry Slack](https://cloudfoundry.slack.com/archives/CFX13JK7B/p1558362092239500?thread_ts=1558362032.239400&cid=CFX13JK7B) from May 2019.

**Comment by geofffranks** [comment]
👋hey @mcwumbly - we believe this is fixed as of [v3.32.0](https://github.com/cloudfoundry/silk-release/releases/tag/v3.32.0).
