### ISSUE TITLE
Metric for container network traffic

### ISSUE THREAD

**Issue by RadiatorSpring** [cloudfoundry/silk-release#27]
## Issue

It would be nice to have a metric that can track the network bandwidth traffic of each app on CF so that we can be more precise when choosing what `rate` and `burst` are best suited for our installation.

## Context

We have tried finding such metric in silk-cni without success maybe we missed something. Also it would be nice to have a general understanding of the needs of the apps on a CF installation have, so that we can warn our customers if they are actively using too much bandwidth

**Comment by ameowlia** [comment]
Hi @RadiatorSpring, 

It also seems related to [this issue on cf-networking.](https://github.com/cloudfoundry/cf-networking-release/issues/64)

I see the value in such metric, however, I don't think we will be able to prioritize it soon. I suggest submitting a proposal (which we can provide feedback on) and a PR if you want to get these features in.

> Also it would be nice to have a general understanding of the needs of the apps on a CF installation have

This is highly dependent on what the app is doing. There is no one-size-fits-all advice for how to manage your CF.

**Comment by MarcPaquette** [comment]
Hi @ameowlia and @RadiatorSpring ,

Is there any further conversation to be had on this topic or is this okay to close out?

Thanks!

**Comment by ameowlia** [comment]
Closing because [this issue ](https://github.com/cloudfoundry/cf-networking-release/issues/64) is finished.
