### ISSUE TITLE
Introduce logs for rate-limited apps in a dry-run mode

### ISSUE THREAD

**Issue by gzvedi** [cloudfoundry/silk-release#39]
## Issue

The current implementation does not support a mode in which only logs are collected when a container is about to get rate-limited. Hence we don't have any means of collecting logs without harming the apps.

## Expected result

When in dry-run mode is possible to provide logging information regarding applications which are to be rate-limited.

## Possible Fix

 - Expose a feature-flag for enabling outbound connections rate limiting only in a dry run mode for collection of logs.
 - When in dry-run mode the rate-limiting should be applied without dropping of any connections.

## Additional Context

➡️   Add a dry-running mode to the feature within silk-cni and expose it through a feature flag.

+Scenarios:+
GIVEN that the rate-limiting is enabled and working_mode is dry_run and logging is turned off
WHEN an application exceeds it rate-limit for outbound connections
THEN the connection is not dropped.

GIVEN that the rate-limiting is enabled and working_mode is dry_run and logging is turned on
WHEN an application exceeds it rate-limit for outbound connections
THEN the connection is not dropped and a log is written that the app outbound connections for the app would've been rate-limited.

**Comment by sleepychild** [comment]
Hello, @Benjamintf1.

The PR #43 from @dezz6ato is ready for review. Unfortunately he left SAP so I had to take over driving the issue. And I also had to take ownership of the code to pass the EasyCLA check.

Kind Regards

**Comment by Benjamintf1** [comment]
I gave it a look, but i also wouldn't clasify myself as a "main maintainer" of silk, so yrmv.

**Comment by sleepychild** [comment]
@Benjamintf1 , I can't access the Concourse build to see what the explosion is. Can you assist?

**Comment by sleepychild** [comment]
@Benjamintf1 ,hello. Can we try this again?

**Comment by sleepychild** [comment]
Hello @Benjamintf1 and @ameowlia.

I just want to make sure it's clear that PR #48 is for this issue here.  If i'm missing something that I should do to get this moving please let me know.

Kind Regards
mario.kukutsov@sap.com

**Comment by geofffranks** [comment]
This has been released in [v3.1.0](https://github.com/cloudfoundry/silk-release/releases/tag/3.1.0) of silk-release
