### ISSUE TITLE
netmon failing to get iptables count

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/silk-release#5]
## Issue

Since upgrading to silk 2.14.0 from 2.9.0 we've noticed the following error in our netmon logs that I thought you'd want to be aware of.  We're not using iptables count currently so this isn't impacting us functionally.

```
{"timestamp":"1536867759.245397329","source":"cfnetworking.netmon","message":"cfnetworking.netmon.measure.failed-getting-filter-rules","log_level":2,"data":{"error":"iptablesCommandRunner: exit status 3 and unlock: \u003cnil\u003e","session":"435"}}
{"timestamp":"1536867759.245450258","source":"cfnetworking.netmon","message":"cfnetworking.netmon.measure.count-iptables-rules","log_level":2,"data":{"error":"iptablesCommandRunner: exit status 3 and unlock: \u003cnil\u003e","session":"435"}}
```

## Context

Upgraded to 2.14.0 and noticed these error logs

## Steps to Reproduce

Deploy cf-deployment 4.1.0+ and notice the errors being logged by netmon.

## Expected result

Expect iptables count to work properly.

## Current result

```
{"timestamp":"1536867759.245397329","source":"cfnetworking.netmon","message":"cfnetworking.netmon.measure.failed-getting-filter-rules","log_level":2,"data":{"error":"iptablesCommandRunner: exit status 3 and unlock: \u003cnil\u003e","session":"435"}}
{"timestamp":"1536867759.245450258","source":"cfnetworking.netmon","message":"cfnetworking.netmon.measure.count-iptables-rules","log_level":2,"data":{"error":"iptablesCommandRunner: exit status 3 and unlock: \u003cnil\u003e","session":"435"}}
```

**Comment by christianang** [comment]
Yep, we noticed this a few days ago and was fixed: https://github.com/cloudfoundry/silk-release/commit/f20c6bf8785d36935f868f401989f432cac91285. It will be included in the next release.

**Comment by youngm** [comment]
Looks good.  Thanks!
