### ISSUE TITLE
Move silk-release jobs into cf-networking-release

### ISSUE THREAD

**Issue by winkingturtle-vmw** [cloudfoundry/silk-release#83]
## Why
Historically cf-networking-release and silk-release releases have been separated with the hope that silk-release would be used outside of CloudFoundry and other plugins for cf-networking would be present. These two releases have to be lock stepped when the time comes to releasing them. Furthermore, this is creating duplicate jobs and an unnecessary jobs when we are bumping golang, healthchecker package, bump dependencies.

**As a** *user*
**I want** *to have the two releases consolidated*
**So that** *all of the jobs are part of a single release and pipeline will no longer need to lock-step releasing these two releases. Additionally, all of the jobs that are repeated for both releases are consolidated into a single release (e.g. bump-golang and bump-healthchecker) *

## What
- Copy blobs and jobs from from silk-release into cf-networking-releases.
- CF-deployment needs to be updated with references pointing to the new version of the release and jobs.
- Silk-release would have README changes pointing folks to cf-networking-release.

## Acceptance Criteria
Silk-release will no longer be a requirement for cf-deployment.

**Comment by ameowlia** [comment]
I am all for consolidating repos and releases where it makes sense, but I think there is a hidden benefit here for having these two separate. Having them separate helps me remember what needs to be replaced when an operator uses a different CNI. For example, for users that user the NCP CNI, they deploy everything in cf-networking-release and nothing from silk-release. I like having that clear boundary.

**Comment by winkingturtle-vmw** [comment]
Thanks for your notes. I can see the advantage of having a release for that reason, but my understanding is that there are jobs even in cf-networking-release (e.g. [policy-server](https://github.com/cloudfoundry/cf-networking-release/tree/develop/jobs)) where it's not really used in a silk-less installation. Is that incorrect? 

Additionally, I think that 3 of the 6 jobs already have a `silk-` prefix, would it be possible to add the same prefix for the remaining jobs to keep the same signature?

**Comment by geofffranks** [comment]
FWIW, policy-server, and policy-server-internal are both used in silk-less installations to manage c2c network policies. Policy-server hosts the [public CF API for networking](https://github.com/cloudfoundry/cf-networking-release/blob/develop/docs/policy-server-external-api.md).

Options I see for this:
1. Consolidate into one boshrelease repo, renaming silk-release jobs with silk-<thing> where needed.
2. Stop releasing cf-networking and silk in lock-step (diverge versions between them).
3. Do nothing.

I don't know that I currently have a preference on any of those. Also curious if there are other ideas out there.

**Comment by geofffranks** [comment]
One concern I have with consolidating is the loss of git history across a lot of code. I assume we'd move this repo into the archive org + archive it, but it still makes cross referencing/git blaming historical changes more difficult.

**Comment by winkingturtle-vmw** [comment]
Thanks for clarifying. Option 2 is interesting and that would remove unnecessary locking we do for testing develop branch of both of these repo together. That said, I am happy with all of the above options. The intention of this issue was to help simplify the daily operation and remove unnecessary jobs we currently have.

**Comment by MarcPaquette** [comment]
Hi @winkingturtle-vmw ,
Are you doing work in this area currently?

**Comment by winkingturtle-vmw** [comment]
Closing this issue, since we decided not to implement it.
